version: '3.3'

services:
  server:
    build: .
    volumes:
      - .:/app
      - ../smtp_project_logs:/usr/src/app/logs
    ports:
      - ${EXTERNAL_PORT}:${CONTAINER_PORT}
    env_file:
      - .env
    container_name: smtp_fastapi
